# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c14e3a931565893c0ea38a1840a50868b31414943d6a52acfa2c4c39deaa3e71621ecbe84de863c256907d6d59be68a73e13fb2b680c2f1bba7b6a33179d93dc

test:
  secret_key_base: d208bd0e1d6212f53faabec17db4e8ba3420b2a3be1b9955590d447c6082ca3de710e50fb917b4d36b833bda013b83d3e5f53f14bd4650e6a7cdee7f8ab9894f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
